[자동차 경주] 이지윤 미션 제출합니다.
gdsc-skhu-pair-mission/java-racingcar-6 pull request #11
Opened 2024-04-09 08:23 UTC by dd-jiyun

## 느낀 점 

test 코드를 작성하고 코드를 작성하니 어떤 흐름을 가지는게 좋은지 미리 생각할 수 있어서 더 좋았던 것 같습니다.

## 궁금한 점
추가적으로 test 코드를 구성할 때 어떻게 쪼개서 테스트를 하는 것이 좋은지 궁금합니다.

---

## 리팩토링 : 공부한 것

### 불변 객체
객체가 생성된 후, 내부의 상태를 변경할 수 없는 객체 (Read-Only 메소드만 제공)

[ 장점 ]

1. Thread-safe 하기 때문에 병렬 프로그래밍에 유용하여 동기화를 고려하지 않아도 된다.
    - 동기화의 문제 원인이 공유 자원을 동시에 쓰기 때문인데, 공유 자원이 불변이라면 항상 동일한 값을 반환하기 때문에 동기화를 고려하지 않아도 된다.
2. 실패 원자적인 메소드를 만들 수 있다.
    - 가변 객체의 경우 예외가 발생하면 객체가 불안정한 상태가 된다. 불안정한 상태를 가진 객체는 변경된 상태로 인해 새로운 에러를 유발할 수 있다. 하지만 불변 객체는 어떠한 예외가 발생하여도 메소드 호출 전의 상태를 유지하기 때문에 추가적인 에러를 막을 수 있다.
3. Cache, Map, Set 등의 요소로 활용하기에 적합하다.
    - 만약 캐시나, Map, Set 등으로 사용되는 객체가 변경되면 이를 갱신하는 작업이 필요한데, 불변 객체의 경우 한 번 데이터가 저장된 이후에 다른 부가 작업을 고려하지 않아도 되어 다른 자료 구조를 사용하는데 용이하다.
4. 부수 효과를 피해 오류 가능성을 최소화할 수 있다.
    - 변수의 값이 변경되거나, 필드 값이 설정되는 등의 변화가 발생하는 효과를 부수 효과라고 하는데, Setter가 구현되어 있거나 여러 메소드에서 객체의 값을 변경하면 객체를 예측하기 어려워지는 단점이 있다. 
    불변 객체는 값의 수정이 불가능하여 변경 가능성이 낮고 객체의 생성과 사용이 제한된다. 그러므로 객체를 안전하게 재사용할 수 있다는 장점이 있다. (유지 보수성이 높음)
5. 다른 사람이 작성한 함수를 예측 가능하게 하며 안전하게 사용할 수 있다.
    - 협업하는 데에 있어서 불변성이 보장된 함수일 경우 다른 사람이 개발한 함수를 위험없이 이용할 수 있다.
6. 가비지 컬렉션의 성능을 높일 수 있다.
    - 가비지 컬렉션 (Garbage Collection[GC]) : 프로그래밍 언어에서 자동으로 동적으로 할당된 메모리 중에서 더 이상 사용하지 않는 객체들을 탐지하고, 해당 객체들의 메모리를 자동으로 회수하는 기능이다.

[단점]

- 매번 메소드를 통해 값을 얻을 때마다 new 연산자를 통해 방어적 복사를 하는데 이렇게 매번 새로운 객체를 생성하는 것이 성능 이슈를 일으킬 수 있다는 생각이 많다. ~~(증명되지 않았고 Oracle에서 객체 생성하는데 드는 비용에 대해 과대평가 되었다는 피셜이 존재한다.)~~

### 디미터의 법칙

최소한의 지식 원칙이라고 불린다. 모듈은 자신이 조작하는 객체의 속사정을 몰라야한다는 것이다.

한 객체가 다른 객체에 대해서 너무 많은 정보를 가지고 있으면 서로에 대한 결합도가 높아지고, 이로 인해 좋지 못한 설계를 하게 된다. 그래서?! 다른 객체에게 어떠한 자료(내부 구조)를 가지고 있는지 숨기고 함수를 통해 공개하는 것이 바로 디미터 법칙이다.

디미터 법칙을 사용하게 되면, 객체의 결합도를 낮출 수 있고 변경에 유연하고 유지보수하기 쉬운 코드를 작성할 수 있다.

2024-04-09 13:28 UTC, hangillee requested changes
안녕하세요, 지윤! 👋

캡스톤 디자인 프로젝트 중에 페어 프로그래밍 미션까지 수행하느라 고생 많았습니다!
클래스 분리, 메소드 분리도 깔끔하게 잘 했고 전반적으로 요구 사항을 잘 준수한 것 같습니다.
몇 가지 더 나아질 부분이 있어서 코멘트 남깁니다!

다음은 남겨주신 질문에 대한 답변입니다!

> 추가적으로 test 코드를 구성할 때 어떻게 쪼개서 테스트를 하는 것이 좋은지 궁금합니다.

결론부터 말씀 드리자면, 테스트 코드는 **기능 명세서 역할**을 담당하기도 합니다.

함께 TDD를 수행하는 동료 개발자가 있다고 가정합시다. 동료 개발자는 TDD를 위해 지윤이 작성한 테스트 코드들을 쭉 훑어볼 것입니다. 프로덕션 코드를 모두 살펴 보기엔 그 양이 방대하고 복잡합니다. 따라서, 어떤 기능들이 구현되어 있고, 어떻게 해야 정상 동작하며, 어떻게 하면 예외가 발생하는지 한 눈에 보여주는 테스트 코드만 읽고 대략적인 프로그램의 설계를 파악할 것입니다.

이후, 동료 개발자는 테스트를 한 번 돌려보고 모두 통과된 것을 확인합니다. 동료 개발자는 지윤이 작성한
코드가 모두 정상임을 확신하고 자신이 맡은 업무를 위해 새로운 테스트 코드를 작성할 것입니다. 나중에 지윤도 동료 개발자가 작성한 테스트 코드를 읽고, 테스트를 실행하고, 또 다시 새 테스트를 작성할 것입니다. 즉, 테스트 코드만으로도 소프트웨어의 모든 기능을 설명하고, 검증해야 합니다. 애초에 TDD를 하게 되면 자연스럽게 구현된 모든 기능에 대한 테스트가 이미 작성되어 있습니다.

따라서 테스트를 위해 무엇을 쪼갠다고 보기 보단, 구현해야 하는 기능에 대한 테스트를 작성했으니, 해당 테스트가 통과되어 명세서로서 작동할 수 있도록 프로덕션 코드를 작성하는 쪽이 더 올바른 방법입니다.

2024-04-09 13:28 UTC, hangillee commented on docs/README.md
> +- 사용자에게 결과를 알려주는 역할을 수행합니다.
기능 구현 목록 작성 👍

2024-04-09 13:28 UTC, hangillee commented on src/main/java/racingcar/controller/RacingCarGameController.java
> +        Racing racing = new Racing(cars, MoveStrategy.RANDOM_4_OR_ABOVE);
상수 이름에 구체적인 경계값을 적어두는 것은 OCP를 위반할 가능성이 있을 것 같습니다!
4가 아니라 3이나 5가 되어버리면 상수 이름도 고쳐야 하는데 이러면 상수를 사용할 이유가 없어집니다.

2024-04-09 13:28 UTC, hangillee commented on src/main/java/racingcar/controller/RacingCarGameController.java
> +    }
Controller에 드러날 이유가 없는 로직인 것 같습니다.
`Cars`라는 일급 컬렉션에서 직접 처리하는게 맞지 않을까요? 🤔

2024-04-09 13:28 UTC, hangillee commented on src/main/java/racingcar/controller/RacingCarGameController.java
> +        }
`stream`을 활용할 수 있을 것 같습니다.

2024-04-09 13:28 UTC, hangillee commented on src/main/java/racingcar/controller/RacingCarGameController.java
> +        }
부정 예약어 `!`는 가독성을 떨어뜨린다는 의견이 있습니다.

`isNaturalNumberWithZero()`를 `isNotNaturalNumberOrZero()`로 바꾸고
메소드 내부의 early return 값들을 `true`로 바꿔보는 것은 어떨까요?

2024-04-09 13:28 UTC, hangillee commented on src/main/java/racingcar/model/Cars.java
> +    }
Stream 활용 👍

2024-04-09 13:28 UTC, hangillee commented on src/main/java/racingcar/model/Car.java
> +    }
이 내용은 굳이 리팩토링에 반영할 필요는 없습니다!

만약, 값을 직접 변경하는 것이 아닌, 새로운 값을 상태로 가지는 객체를 생성해서 반환한다면..?
`Car` 객체는 불변 격체가 될 수 있지 않을까요? 불변 객체(immutable object)의 장점과 단점은 무엇이 있을까요?
고민해봅시다! 😁

2024-04-09 13:28 UTC, hangillee commented on src/main/java/racingcar/model/Judgement.java
> +                .filter(name -> cars.getPositions().get(cars.getNames().indexOf(name)) == maxPosition)
`Cars`의 내부 구현을 너무 훤히 들여다보고 있는 것 같습니다.
디미터의 법칙에 대해 학습해보고 역할과 책임을 적절하게 재분배하여 `.` 연산자를 줄여봅시다.

p.s. `.stream()`도 앞에 `.`가 있다면 개행해주는 것이 좋습니다!

2024-04-09 13:28 UTC, hangillee commented on src/main/java/racingcar/model/MoveStrategy.java
> +}
전략 패턴을 도입한 것으로 보이는데 맞나요?

지금 당장은 꽤 괜찮은 방법의 전략 패턴 구현이지만 추후의 확장을 생각한다면
열거형 보다는 인터페이스를 통한 추상화 방식이 더 나을 것 같습니다!

2024-04-09 13:28 UTC, hangillee commented on src/main/java/racingcar/model/Racing.java
> +    }
적절한 추상화 계층 생성을 통한 깔끔한 도메인 클래스 코드 👍

2024-04-09 13:28 UTC, hangillee commented on src/main/java/racingcar/util/RandomNumberGenerator.java
> +    }
`private` 생성자 👍

중간의 개행은 없어도 무방할 것 같습니다!

2024-04-09 13:28 UTC, hangillee commented on src/test/java/racingcar/model/CarTest.java
> +}
POSIX New Line에 대해 학습해봅시다!

모든 코드 파일의 마지막에는 공백 라인이 있어야 합니다!
IntelliJ의 New Test 기능을 통해 테스트 코드 파일을 생성하면 마지막 줄에 공백 라인이 없으므로 주의해야 합니다.

2024-04-09 13:28 UTC, hangillee commented on src/test/java/racingcar/model/CarsTest.java
> +    void 정상적으로_자동차들_객체_생성() {
테스트 메소드의 이름은 영어로 작성하는 것이 권장됩니다.
희박한 확률이지만 한글을 지원하지 않는 인코딩을 가진 IDE로 해당 프로젝트를 열었을 시에 제대로 동작하지 않을 가능성이 있습니다.

대신 `@DisplayName` 어노테이션을 활용해봅시다!

2024-04-09 13:28 UTC, hangillee commented on src/test/java/racingcar/model/CarTest.java
> +        assertThatThrownBy(() -> new Car(name))
예외 상황에 대한 테스트 작성 👍

2024-04-11 02:07 UTC, dd-jiyun commented on src/test/java/racingcar/model/CarsTest.java
> +    void 정상적으로_자동차들_객체_생성() {
@DisplayName을 활용하여 메소드를 작성하고 있는데 Test 코드 메소드 명을 어떻게 구성하면 좋을 지 고민하는 중입니다.
되게 여러 가지 방법이 있던데 한길님은 어떤 테스트 코드 메소드 명을 선호하시나요?!

2024-04-11 05:24 UTC, dd-jiyun commented on src/main/java/racingcar/util/RandomNumberGenerator.java
> +    }
위처럼 생성자 선언 시 비어있으면 모두 중간 개행이 없어도 되는건가요?

2024-04-12 12:20 UTC, hangillee commented on src/main/java/racingcar/util/RandomNumberGenerator.java
> +    }
네 맞습니다! 굳이 불필요한 개행을 할 이유는 없습니다.

2024-04-12 12:21 UTC, hangillee commented on src/test/java/racingcar/model/CarsTest.java
> +    void 정상적으로_자동차들_객체_생성() {
저는 일반 메소드와 다르지 않은 작명법을 활용합니다. 테스트 코드도 일단은 코드니까요!

2024-04-15 10:30 UTC, hangillee requested changes
안녕하세요, 지윤! 👋

전반적으로 잘 리팩토링 해주셔서 몇 부분 제외하고는 더 이상 고쳐야 할 부분은 보이지 않는 것 같습니다. 또한, 제가 제안한 학습해볼만한 지식들도 스스로 잘 학습한 것 같아서 뿌듯합니다.

조금 더 수정해주시고, 다음 리뷰 요청에서 특이사항이 없다면 Merge 하겠습니다!

2024-04-15 10:30 UTC, hangillee commented on src/main/java/racingcar/model/Cars.java
> +    }
정적 팩토리 메소드 활용 👍

2024-04-15 10:30 UTC, hangillee commented on src/main/java/racingcar/model/Judgement.java
> +    }
아무리 `private` 생성자라고 해도 생성자는 상수, 멤버 변수 다음에 오는 것이 Java 컨벤션입니다.
이 위치에 두는 것은 좋지 않은 것 같습니다!

2024-04-15 10:30 UTC, hangillee commented on src/main/java/racingcar/model/MoveStrategy.java
> +}
인터페이스를 활용한 추상화 계층 설계

2024-05-03 12:58 UTC, dd-jiyun commented
추가적으로 생성자 위치만 변경했습니다! @hangillee

2024-05-10 01:26 UTC, hangillee requested changes
한 가지 고쳐야할 게 있어서 다시 한번 RC 남깁니다!
확인해주세요~ 미션 고생하셨어요!

2024-05-10 01:26 UTC, hangillee commented on .gitignore
> +*.DS_Store
EOL! 항상 마지막 줄은 공백 라인으로!

2024-05-10 01:26 UTC, hangillee commented on src/main/java/racingcar/model/Judgement.java
> +
생성자 위치 좋아요! 👍

2024-05-13 04:50 UTC, hangillee approved these changes

2024-05-13 04:51 UTC, merged