[자동차 경주] 김신희 미션 제출합니다.
gdsc-skhu-pair-mission/java-racingcar-6 pull request #12
Opened 2024-04-09 08:29 UTC by shinheekim

## 실행 과정
1. 기능 정리를 README파일에서 명시하고 코드 작성
2. 온라인으로 진행했지만 한 컴퓨터에서 작성하는 것과 같은 환경을 위해 JetBrains에서 제공하는 Code With Me를 활용하여 본인의 intellij project 내에서 함께 이어 작성

## 어려웠던 점/이에 대한 개발 방법
- MVC 패턴으로 코드를 짜기 위해 여러 패키지로 나눴다가, 각각의 클래스에 대한 역할을 명확하게 나누기 어려워 최소화하여 작성했습니다. Controller는 View에서 사용자에게 입력받아 Model에서 로직을 실행시킬 수 있도록 코드를 작성했습니다.
 - 모델 분리 확실 x
- TDD 위주의 설계를 해보고 싶었지만 MVC 패턴 작성과 test code 작성 모두 익숙하지는 않아 test code는 추후에 작성하게 되었습니다. 참고로 test code는 개발 중 고민이 많았던 '우승자 추출'부분을 작성해보았습니다. 

## 궁금한 점
- 어떻게 하면 확실하게 각 계층으로 나눠 역할을 지정해줄 수 있을지에 대한 피드백

2024-04-10 11:55 UTC, hangillee requested changes
안녕하세요, 신희! 👋

리뷰가 다소 늦어진 점 죄송합니다.. 생소한 요구 사항이 주어져 여러모로 힘든 미션이었을텐데 잘 진행해주셨네요! MVC 패턴을 적용하겠다고 미리 패키지를 나누고 클래스를 분배하는 것은 조금 힘든 일일 겁니다. 도메인 지식이 충분히 쌓여있는게 아닌 이상 모든 것을 처음부터 완벽하게 설계할 순 없죠. 😁 그래서 `In -> Out`, `Out -> In` 방법을 적절히 섞어서 설계하는 것을 추천합니다.

TDD 위주의 설계도 사실 도메인 지식이 쌓여 있어야 수월한 편입니다. 무슨 기능이 필요하고 해당 기능은 어떤 객체가 가져야 할지 판단하는 것도 결국 도메인에 대해 잘 알아야 하기 때문이죠. 자동차 경주 미니 게임은 언뜻 보면 쉬워보이지만 우리가 평소에 자주 생각하는 개념은 아니라 조금 어려웠을 겁니다.

추가로, 테스트 코드는 선택적으로 작성하는 것이 아닙니다. 우리가 설계한 도메인의 **모든 기능**에 대해 작성해야 합니다.(입출력과 같은 Java 라이브러리에 대해선 따로 테스트 하지 않아도 됩니다.) 지금은 익숙치 않아서 고민했던 부분만 작성한 것은 이해하지만, 앞으로는 테스트 코드에 조금 더 신경써봅시다! 어려운 길이겠지만 저도 열심히 도와드릴게요!

다음은 남겨주신 질문에 대한 답변입니다!

> 어떻게 하면 확실하게 각 계층으로 나눠 역할을 지정해줄 수 있을지에 대한 피드백

이건 사실 계속 말씀드렸던 도메인 지식을 쌓는 방법 밖엔 없습니다. 저도 처음부터 계층을 명확하게 나누진 못합니다. 다만, 각 계층(Model, View, Controller)가 하는 보편적인 역할은 확실하게 알아둘 필요가 있습니다. Model은 핵심 비즈니스 로직들, View는 사용자와의 상호 작용(입출력), Controller는 Model과 View 사이의 중재자 역할을 가집니다.

즉, Controller에 비즈니스 로직(무슨 조건일 때, 얼만큼 이동한다 같은...)을 두면 당연히 좋지 않습니다. 해당 로직은 Model이 가져야하는 것은 명백한 MVC 패턴의 규칙이니까요! 신희가 사용할 여러 디자인 패턴의 핵심 원리가 무엇인지 확실하게 학습하고 사용하면 계층 별로 역할과 책임을 나누는 것은 그리 어렵지 않을 겁니다! 리팩토링 파이팅입니다!

2024-04-10 11:55 UTC, hangillee commented on docs/README.md
> +>>>>>>> b43ad53ab574757b955998ccc66fbb875e3e45ee
Conflict 발생한 부분 지워줍시다. 보통 `HEAD`가 있는 부분이 최신일 가능성이 높습니다.

2024-04-10 11:55 UTC, hangillee commented on docs/README.md
> +>>>>>>> b43ad53ab574757b955998ccc66fbb875e3e45ee
기능 구현 목록 작성 👍

2024-04-10 11:55 UTC, hangillee commented on src/.DS_Store
`.gitignore` 파일에 `.DS_Store`를 추가해줍시다.

2024-04-10 11:55 UTC, hangillee commented on src/main/java/racingcar/controller/GameController.java
> +}
POSIX New Line에 대해서 학습해봅시다!

모든 코드 파일의 마지막 줄엔 공백 라인이 있어야 합니다.

2024-04-10 11:55 UTC, hangillee commented on src/main/java/racingcar/controller/GameController.java
> +    public void Racing(int repeat) {
메소드 이름은 소문자로 시작해야 합니다. 컨벤션을 지켜주세요!

2024-04-10 11:55 UTC, hangillee commented on src/main/java/racingcar/controller/GameController.java
> +            OutputView.showCar(cars);
View 계층에 `Cars` 도메인을 그대로 넘겨주고 있네요!
이렇게 하면 MVC 계층을 나눈 이유가 사라지는 것 같아요. 로직을 수정해봅시다!

2024-04-10 11:55 UTC, hangillee commented on src/main/java/racingcar/domain/Car.java
> +        position++;
만약, `position`을 변경하는 것이 아닌, 새 `position` 값을 가지는 `Car` 인스턴스를 새로 만들어서 반환한다면...?
불변 객체의 장단점에 대해서 학습하고 왜 제가 이런 방식을 추천했는지 고민해보시는 걸 추천합니다!

2024-04-10 11:55 UTC, hangillee commented on src/main/java/racingcar/domain/Cars.java
> +    private static final int MINIMUM_POSITION = 0;
보통 `static final`로 선언하게 되는 상수를 멤버 변수보다 위에 두고 둘을 공백 라인을 통해 구분합니다.
이는 `Google Java Style Guide`에 있는 컨벤션으로 지켜주셔야 합니다!

2024-04-10 11:55 UTC, hangillee commented on src/main/java/racingcar/domain/Cars.java
> +        }
`stream`을 사용하거나 메소드 분리를 통해 `indent` 깊이를 1로 줄일 수 있을 것 같아요!
리팩토링 도전해봅시다! 😁

2024-04-10 11:55 UTC, hangillee commented on src/main/java/racingcar/domain/Cars.java
> +        }
마찬가지로 `stream`을 활용하거나 메소드 분리를 통해 `indent`를 1로 줄여봅시다!
크게 어렵지 않을거에요.

2024-04-10 11:55 UTC, hangillee commented on src/main/java/racingcar/validate/CarNameValidate.java
> +            }
이 친구들도 메소드 분리해봅시다. `if` 블록 하나씩 메소드로 분리해서 메소드 이름을 통해 의미를 부여하면,
굳이 내부에서 어떻게 검증하는지 알지 못해도 `validateCarName` 메소드가 어떤 것들을 검증하는지 알 수 있습니다.

2024-04-10 11:55 UTC, hangillee commented on src/main/java/racingcar/view/InputView.java
> +
불필요한 공백 라인 제거해봅시다.
앞에서도 설명드렸던 것처럼 공백 라인도 컨벤션이 될 수 있습니다.

2024-04-10 11:55 UTC, hangillee commented on src/main/java/racingcar/validate/CarNameValidate.java
> +    public static void validateCarName(String[] carNames){
`static` 메소드 하나만 있는 Util 클래스는 생성자를 `private`으로 막아주어야 합니다.
왜 그래야 하는지도 학습해봅시다!

2024-04-10 11:55 UTC, hangillee commented on src/main/java/racingcar/validate/CarNameValidate.java
> +            if(carName.length() < 1){
다른 조건으로 대체 가능할 수도 있을 것 같습니다.
Java에서 제공해주는 메소드를 활용해봅시다!

2024-04-10 11:55 UTC, hangillee commented on src/main/java/racingcar/domain/Cars.java
> +                car.moveForward(); // position++;
주석은 해당 코드가 왜 그 위치에 있어야 하는지 설명하는데 사용합니다.
코드의 동작을 설명하는 주석은 궁극적으로 제거되어야 합니다.

이미 메소드 이름만으로 무슨 동작을 하는지 충분히 파악 가능하니 주석은 제거해주세요!

2024-04-10 11:55 UTC, hangillee commented on src/main/java/racingcar/view/OutputView.java
> +
불필요한 공백 라인이 있네요..

PR 작성 전, `SonarLint`와 같은 플러그인을 실행시키고 제출하는 것을 추천합니다.
나중에 실무나 팀 프로젝트에 들어갔을 때 이런 사소한 실수라도 협업하는 개발자의 집중력을 확 떨어뜨릴 수 있습니다.

2024-04-10 11:55 UTC, hangillee commented on src/main/java/racingcar/view/OutputView.java
> +public class OutputView {
둘 사이에 개행이 필요한 것 같습니다.

`CarNameValidate`와 마찬가지로, `InputView`나 `OutputView` 모두 `static` 메소드 밖에 없으니 Util 클래스라 볼 수 있을 것 같습니다. 적절하게 필요한 조치를 취해봅시다!

2024-04-10 11:55 UTC, hangillee commented on src/test/java/racingcar/ApplicationTest.java
> +
추가해주신 테스트는 `Cars`에 대한 테스트인 것 같습니다.
`ApplicationTest`에 있기 보단 새로운 테스트 클래스를 추가해 봅시다.

2024-04-11 08:17 UTC, shinheekim commented on src/.DS_Store
![image](https://github.com/gdsc-skhu-pair-mission/java-racingcar-6/assets/128473266/c654266c-5352-4cde-9f7a-7fcda7b079ad)
포함되어있는 것으로 확인됩니다!!

2024-04-11 08:21 UTC, shinheekim commented on src/.DS_Store
앗 window로 프로젝트 생성하고 mac사용자 페어와 서로 풀 푸쉬 하는 동안 .DS_Store 파일이 생겼군요!! 감사합니다

2024-04-11 08:34 UTC, shinheekim commented on src/main/java/racingcar/domain/Car.java
> +        position++;
사실 이 moveForward 메서드에서 고민이 많이 됐습니다...이렇게 되는게 맞나 싶었는데 정확히 짚어주신 거 같네요..! 좋은 방식 감사드립니다!

2024-04-11 08:41 UTC, shinheekim commented on src/main/java/racingcar/domain/Cars.java
> +    private static final int MINIMUM_POSITION = 0;
페어와 작성하다보니 컨벤션이 지켜지지 않은 부분인 거 같네요. 좋은 지적 감사합니다!! `앞으로 주의~~`

2024-05-10 02:02 UTC, hangillee approved these changes
미션 고생 많으셨어요! 다음 미션도 파이팅!

2024-05-10 02:02 UTC, merged