[자동차 경주] 최인호 미션 제출합니다.
gdsc-skhu-pair-mission/java-racingcar-6 pull request #4
Opened 2024-04-08 15:26 UTC by inhooo00

### 어려웠던 점
- 테스트코드가 서로 처음이라 많이 헤맸습니다. 
- 메서드를 얼마나 분리해야하는지 계속해서 고민해 보았습니다. 사람마다의 관점에 따라 다른 것이, 즉 정답이 없다는 것이 어려웠습니다.

### 궁금한 점
- outputveiw에서 -2가 하드코딩으로 구현했는데 값을 다시 바꿀 일이 없을 거 같아서 이렇게 작성하였습니다. 옳은 선택일까요??
- 더 메서드 분리 혹은 반대로 통합해야할 부분이 있을지 궁금합니다.

+
![image](https://github.com/gdsc-skhu-pair-mission/java-racingcar-6/assets/129029251/8f04a3d4-6c90-44e7-86d1-f839c1f26a25)
테스트 커버리지 사진

2024-04-09 10:31 UTC, hangillee requested changes
안녕하세요, 인호! 👋

시험 기간에 미션 진행하느라 고생 많았습니다! 단위 테스트 작성을 스스로 학습하고 적절하게 작성해주신 것 같네요. 테스트 코드는 많이 작성하다보면 익숙해질 거라 생각합니다. 저도 그랬으니까요!

메소드 분리에 대한 기준은 어찌보면 간단합니다.
제가 메소드를 작성할 때 고려하는 사항은 다음과 같습니다.
1. 지금 메소드는 읽기 쉬운가? (메소드 시그니처만으로 무슨 일을 하는지 이해할 수 있어야 합니다.)
2. 지금 메소드는 하나의 일만 하는가?
3. 지금 메소드는 테스트하기 쉬운가?
4. 지금 메소드는 제대로 테스트 되는가?

핵심은, 메소드 분리는 **좋은 코드를 위해 필요한 과정**이라는 것입니다. 메소드 분리는 코드의 가독성을 위함이고, 코드의 가독성은 좋은 퀄리티의 코드를 만들고, 좋은 퀄리티의 코드는 유지보수하기 쉬워지며, 유지보수하기 쉬워진 코드는 협업하는 다른 개발자에게도 도움이 됩니다.

남겨주신 질문에 대한 답변은 리뷰 코멘트에 남겨 두었습니다!

2024-04-09 10:31 UTC, hangillee commented on docs/README.md
> +# 1차 리뷰 후 개선 방향
기능 구현 목록 작성 👍

2024-04-09 10:31 UTC, hangillee commented on src/main/java/racingcar/controller/RacingCarGameController.java
> +    List<Car> cars = new ArrayList<>();
이 친구를 Controller가 상태로 가져도 괜찮을까요?
**일급 컬렉션**이라는 개념에 대해 학습해봅시다!

2024-04-09 10:31 UTC, hangillee commented on src/main/java/racingcar/controller/RacingCarGameController.java
> +        System.out.println(carNames);
불필요한 출력인 것 같습니다. 요구 사항에는 따로 없었던 것 같아요.

2024-04-09 10:31 UTC, hangillee commented on src/main/java/racingcar/controller/RacingCarGameController.java
> +        }
이 일련의 과정이 위에서 언급한 일급 컬렉션을 사용하면 Controller에 없어도 될 로직 같아 보입니다.
Controller가 입력 받은 이름 검증과 `Car` 객체 생성에 대한 책임을 가지는게 맞을지도 고민해봅시다!

2024-04-09 10:31 UTC, hangillee commented on src/main/java/racingcar/model/Car.java
> +    }
`setter`를 사용하셨네요. 불변 객체(immutable object)의 장점에 대해 학습해봅시다.
설령, `setter`의 역할을 하는 메소드를 만들었다고 해도, 이 메소드는 `move`라는 이름을 가지는게 더 나을 것 같습니다.
코드의 퀄리티를 높이기 위해서는 오용하기 어렵게 만들어야 합니다. `setMovement`보다는 `move`가 혼동하기 어려울 것 같아요.

2024-04-09 10:31 UTC, hangillee commented on src/main/java/racingcar/util/ErrorMessage.java
> +    public final String message;
이 두 줄 사이에 개행이 있으면 좋을 것 같습니다.

2024-04-09 10:31 UTC, hangillee commented on src/main/java/racingcar/util/ErrorMessage.java
> +    INPUT_WRONG_ROUND_NUMBER("입력한 라운드 수가 올바르지 않습니다.");
에러 메시지를 `enum`으로 따로 분리해둔 이유가 있을까요?
만약, 에러 발생 이유가 달라진다면, 해당 에러가 발생하는 클래스를 먼저 확인할 것 같은데 어떻게 생각하나요?

2024-04-09 10:31 UTC, hangillee commented on src/main/java/racingcar/util/Parser.java
> +    }
Util 클래스의 장점과 단점은 무엇일까요?
이 기능들은 그렇게 많은 클래스에서 사용되는 것 같진 않은데 분리해 둔 이유가 있나요?

2024-04-09 10:31 UTC, hangillee commented on src/main/java/racingcar/util/Random.java
> +    }
마찬가지로 `Randoms`를 그대로 사용하지 않은 이유가 있나요?

2024-04-09 10:31 UTC, hangillee commented on src/main/java/racingcar/util/Validator.java
> +     * */
주석이 없어도 충분히 이해할 수 있게 메소드 시그니처를 적어두는게 낫습니다.
주석은 해당 코드가 왜 그 위치에 있어야 하는지 설명하기 위해서 사용해야 합니다.

즉, 코드가 무슨 역할과 책임을 가지는지는 코드로만 설명 가능해야 합니다.

2024-04-09 10:31 UTC, hangillee commented on src/main/java/racingcar/util/Validator.java
> +    }
제 생각에는 이 `Validator` 클래스는 가진 역할과 책임이 너무 많은 것 같습니다.
`Car`에 대한 검증, `Referee`에 대한 검증까지, 왜 하나의 거대한 Util 클래스인 `Validator`가 모두 가지고 있어야 하나요?

**응집도**와 **결합도**에 대해서 학습해봅시다! 그리고, 거대해졌거나 불필요한 Util 클래스들을 없애봅시다.

2024-04-09 10:31 UTC, hangillee commented on src/main/java/racingcar/view/OutputView.java
> +    }
분명 다른 방법이 있을 겁니다! `-2` 같은 매직 넘버를 활용하는 로직은 다른 개발자가 이해하기 어렵습니다.

2024-04-09 10:31 UTC, hangillee commented on src/test/java/racingcar/model/CarTest.java
> +        Assertions.assertEquals(INPUT_CAR_NAME_IS_INCORRECT.message, exception.getMessage());
한 테스트 메소드에서는 하나의 `assert`만 해야 합니다.
`AssertJ`의 `assertThatThrownBy`에 대해 학습해봅시다.

2024-04-09 10:31 UTC, hangillee commented on src/test/java/racingcar/model/CarTest.java
> +    void 자동차_이름_5글자_이상일_때() {
테스트 메소드 이름은 영어로 해두는 편이 낫습니다.
희박한 가능성이지만, 한글이 지원되지 않는 IDE에서 해당 테스트 코드의 메소드 이름이 깨져 동작하지 않을 수도 있습니다.

대신 `@DisplayName`에 대해 학습해봅시다.

2024-04-09 10:31 UTC, hangillee commented on src/test/java/racingcar/model/CarTest.java
> +    }
메소드 이름만 보면 경계값 테스트로 보이나, 4 이상일 경우에 대한 테스트에서 주어진 값은 6입니다.
경계값 테스트에 대해 학습해봅시다!

2024-04-09 10:31 UTC, hangillee commented on src/test/java/racingcar/model/RefereeTest.java
> +    }
여러 경우에 대한 테스트 👍

2024-04-09 12:16 UTC, inhooo00 commented on src/main/java/racingcar/util/Parser.java
> +    }
지금은 많은 기능에 사용되지 않는 기능이라도, 후에 개발이 커졌을 경우 다시 사용될 수 있을 기능인 것 같아 따로 만들어 봤습니다!!

2024-04-09 12:20 UTC, inhooo00 commented on src/main/java/racingcar/model/Car.java
> +    }
메서드 이름 다시 한 번 고민해 보겠습니다!

2024-04-09 12:31 UTC, inhooo00 commented on src/main/java/racingcar/util/ErrorMessage.java
> +    INPUT_WRONG_ROUND_NUMBER("입력한 라운드 수가 올바르지 않습니다.");
저번 과제에서는 enum을 사용해보지 않았기에, 이번 과제에서는 한 번 사용해볼까? 라는 생각과 함께 진행했던 것 같습니다. 
한길님 말대로 에러가 발생하면 해당 클래스를 먼저 확인하는 것이 맞는 거 같습니다. enum을 사용하면 에러의 근본 원인을 파악하기 어려울 거 같습니다.
저는 이번에 enum을 통해 "에러 메시지 관리"의 차원으로 접근해서 작성했다고 생각합니다. 
에러 원인 파악은 해당 클래스에서 하고, 에러 메세지 관리는 enum을 통해 한다! 서로 상호보완적인 관계로 접근해 보았습니다.

2024-04-09 12:32 UTC, inhooo00 commented on src/main/java/racingcar/controller/RacingCarGameController.java
> +        }
contrller의 역할에 대해 다시 한 번 고민해 보겠습니다!

2024-04-09 13:14 UTC, inhooo00 commented on src/main/java/racingcar/util/Random.java
> +    }
메서드가 최대한 한 번에 한 기능만 사용하도록 하기 위해 따로 만들었습니다!

2024-04-09 13:58 UTC, hangillee commented on src/main/java/racingcar/util/Parser.java
> +    }
여러 곳에서 활용할 수 있는 기능을 한 곳에 모아두는 것은 좋지만, 제대로 추상화되지 않을 경우, 사소한 수정에 의한 파급 효과가 상상 이상으로 커질 수 있습니다. 지금 당장은 문제가 없어 보여도, 항상 미래를 생각해보는 것을 추천합니다!

2024-04-11 04:26 UTC, inhooo00 commented on src/main/java/racingcar/view/OutputView.java
> +    }
매직 넘버는 이해하기 어렵다는 관점으로 다가가 이름을 만들어주는 느낌으로 따로 빼겠습니다!

2024-04-12 12:46 UTC, hangillee requested changes
안녕하세요, 인호! 👋

리팩토링 잘 해주셨네요! 몇 가지 더 고쳐봤으면 싶은게 있어서 코멘트 남겨드립니다.
남은 시간 동안 파이팅!

2024-04-12 12:46 UTC, hangillee commented on src/main/java/racingcar/controller/RacingCarGameController.java
> +
불필요한 공백 라인!

2024-04-12 12:46 UTC, hangillee commented on src/main/java/racingcar/controller/RacingCarGameController.java
> +    }
Controller가 굳이 알아야 할 로직일까요?
Controller는 어떤 방식으로 자동차가 움직이는지 모른채 단순히 `move` 정도의 메시지만 보내는게 맞을 것 같습니다.

이 로직을 적절한 도메인에게 위임합시다.

2024-04-12 12:46 UTC, hangillee commented on src/main/java/racingcar/model/Car.java
> +    private final String NAME;
상수라면 `static` 키워드를, 변수라면 소문자로 작성해주세요.

제가 이해하기로는 `MIN_FORWARD_REQUIREMENT`는 상수고 `NAME`은 변수인 것 같은데
`MIN_FORWARD_REQUIREMENT`는 `static` 키워드를, `NAME`은 소문자가 더 어울릴 것 같습니다.

이름이 한번 할당된 후에는 변경되지 않는다 하더라도, `4`라는 상수와는 다르게 어떤 문자열 값을 넣어
`Car` 인스턴스를 생성하냐에 따라 각 인스턴스는 서로 다른 값을 가지므로 **재할당 불가 변수**로 보는 것이 더 합리적입니다.

2024-04-12 12:46 UTC, hangillee commented on src/main/java/racingcar/model/Cars.java
> +        List<String> carNames = Parser.parseStringToList(input);
전 아직도 `Parser`가 꼭 필요했을지 의문이네요..
`Cars`를 제외하곤 딱히 효율적으로 활용할 수 있는 Util 클래스라고 생각되진 않습니다.

2024-04-12 12:46 UTC, hangillee commented on src/main/java/racingcar/util/ErrorMessage.java
> +    INPUT_WRONG_ROUND_NUMBER("입력한 라운드 수가 올바르지 않습니다.");
좋은 아이디어입니다! 👍

다만, 조심해야하는 점은 해당 클래스를 생성한 순간 모든 클래스의 에러 메시지를 해당 클래스에서 관리할 것을 기대하게 됩니다. 즉, **어느 클래스에서는 직접 에러 메시지를 관리**하고 **어떤 클래스에서는 이 `ErrorMessage`에서 관리**하게 될 가능성이 존재하는 한, 조금 위험한 방식입니다.

만약, 다른 개발자가 `ErrorMessage`에서 관리해야 한다는 것을 잊고 클래스에서 직접 에러 메시지를 상수로 관리하게 구현했다고 가정하면, 나중에 인호나 또 다른 개발자들은 에러 메시지를 고치기 위해 이 클래스를 아무리 뒤져도 찾지 못하게 될 가능성이 존재합니다. 지금은 충분히 납득할만한 코드지만 미래를 생각했을 때는 그렇게 수명이 긴 코드라고 볼 수 없을 것 같습니다.

2024-04-12 12:46 UTC, hangillee commented on src/main/java/racingcar/view/OutputView.java
> +    public void printWinners(List<Car> winnerCars) {
`List<Car>`로 받아온 덕분에 `Car`의 공개 API들을 모두 `OutputView`에서 사용할 수 있게 되었습니다. 이는 MVC 패턴을 제대로 사용하지 못하고 있다는 신호입니다. 계층이 제대로 분리되지 못하고 Model이 View까지 이동했으니까요.

리팩토링의 시간입니다!

2024-04-12 12:46 UTC, hangillee commented on src/test/java/racingcar/model/CarTest.java
> +    @DisplayName("차 이름이 5글자 이상일 때")
`@DisplayName`에서는 이 테스트 메소드가 어떤 상황을 검증하는 것인지 명확하게 작성해주세요!
제 생각에는 `5글자 이상일 때 예외가 발생한다.` 정도가 될 것 같네요.

2024-04-13 18:04 UTC, inhooo00 commented
어떻게든 결합도를 완화시키려고 dto를 사용해보았습니다. 
Controller에서 List<Car>와 List<CarNameDto> 사이에 엄청난 타입 이슈로 머리를 싸맨 결과 
제 부족한 지능으로 인해 좀 지저분해 보이게 만들 수 밖에 없었습니다...
하지만 처음에 생각한 모델과 뷰 사이에 과도한 결합도는 해결하지 않았을까 생각합니다!

2024-04-15 10:45 UTC, hangillee requested changes
안녕하세요, 인호! 👋

리팩토링 잘 해주셨네요! 결합도를 낮추기 위해 DTO를 도입했다는 경험만으로 왜 DTO를 사용하는지에 대한 답을 찾을 수 있었을 겁니다. 몇가지 더 수정할 부분만 수정해주시면 좋을 것 같아요.

제가 보기에도 충분히 결합도는 낮아진 것 같습니다. 이번 수정 이후에 Merge하겠습니다!

2024-04-15 10:45 UTC, hangillee commented on src/main/java/racingcar/model/Cars.java
> +        List<String> carNames = Arrays.asList(input.split(","));
사실 이 부분 자체가 `String input`을 매개변수로 받는게 아닌, `List<String> names`를 받게 되면 View와의 결합도가 많이 낮아지게 됩니다. 지금 코드는 사용자의 입력이 콤마를 기준으로만 주어질 것이라고 미래를 "예측"한 것과 다르지 않습니다. 즉, View에서 콤마가 아니라 세미콜론을 기준으로 구분한다면 View뿐만 아니라 Model의 코드까지 모두 고쳐야 하는 것입니다. 사소한 입출력 변화가 Model의 코드까지 영향을 받는 것은 분명 좋지 않은 상황이죠.

`Cars`가 `InputView`로부터 받아온 문자열을 `split()`하는 것이 올바른 역할과 책임 분배인지 다시 한번 생각해봅시다.

2024-04-15 10:45 UTC, hangillee commented on src/test/java/racingcar/model/CarTest.java
>      void CAR_NAME_MORE_THAN_5_CHARACTERS_EXCEPTIONS_HANDLING() {
테스트 코드도 코드입니다!

우리는 프로덕션 코드에서 이렇게 메소드 이름을 작성하진 않습니다. `CAR_NAME_MORE_THAN_5_CHARACTERS_EXCEPTIONS_HANDLING`과 같은 모습은 상수를 작성할 때 사용하는 표기법이며, Google Java Style Guide에서는 메소드 이름으로 카멜 케이스를 사용할 것을 안내하고 있습니다.

2024-04-15 10:45 UTC, hangillee commented on src/main/java/racingcar/dto/CarNameDto.java
> +public class CarNameDto {
DTO 활용 👍

결합도를 낮추기 위해 해결책으로 DTO를 사용하는 결론에 도달했군요!
앞으로 인호에게 누군가 "왜 DTO를 사용하는가?"에 대해 묻는다면 이번 경험이 그 답이 될 겁니다!

2024-05-10 01:33 UTC, hangillee requested changes
미션 고생 많으셨습니다! 조금 더 생각해볼 부분들이 있어서 한 번 더 RC 드렸습니다.
리팩토링 부탁드려요~

2024-05-10 01:33 UTC, hangillee commented on src/main/java/racingcar/controller/RacingCarGameController.java
> +    }
한 메소드에서 여러 일을 하고 있는 것 같아요. 조금 분리할 수 있지 않을까요?

2024-05-10 01:33 UTC, hangillee commented on src/main/java/racingcar/model/Referee.java
> +    public List<Car> judgementWinnerCars(List<Car> cars) {
`Cars`라는 일급 컬렉션이 있는데 굳이 컬렉션으로 받은 이유가 있나요?

2024-05-10 01:33 UTC, hangillee commented on src/test/java/racingcar/model/RefereeTest.java
> +    }
`@ParameterizedTest`에는 `@NullAndEmptySource`도 활용할 수 있다는 걸 알고 계시나요?
사용을 고려해보시는 건 어떤가요?

2024-05-13 04:51 UTC, hangillee approved these changes

2024-05-13 04:52 UTC, merged