[자동차 경주] 김우진 미션 제출합니다.
gdsc-skhu-pair-mission/java-racingcar-6 pull request #6
Opened 2024-04-08 20:29 UTC by woogym

## 어려웠던점
- 이번 미션을 진행하면서 model설계에 가장 많은 고민을 했습니다 각각의 역할과 책임을 분배하는 과정에서 페어와 많은 대화도 나누고 고민도
했습니다.  객체의 역할과 책임을 분배하는 과정이 익숙하면서도 고민을 많이 하게 되었습니다
-  알고리즘이 약하다보니 구현을 하는 과정에서 효과적인 로직을 설계하는데 페어의 도움을 많이 받았습니다

## 궁금한점
- mvc패턴으로 구현하였는데 잘 지켜졌는지 궁금합니다
- controller 테스트 코드를 작성하는데 어려움을 느끼고 결국 완성하지 못했습니다, 테스트 코드를 잘 작성하기 위해서 어떤식으로 
코드의 구성과 접근방식이 궁금합니다
- 또한 객체 설계에 많은 고민을 했었습니다 페어와 많은 상의를 했었을때 Car, Cars, Race, MoveDecider 이렇게 모델을 4개로 분리했었는데 
많은 상의 끝에 지금 제출한 형태로 3개가 되었습니다 모델 분리에 있어서 피드백을 받고싶습니다!

2024-04-11 07:53 UTC, HanHyunsoo requested changes
안녕하세요 우진님 리뷰어 한현수입니다.

코드가 되게 완성도 있네요 하지만 아쉬운 부분이 있어 댓글 참고하시고 수정하시면 좋을 것 같습니다.

### 궁금한 점에 대한 답변

* mvc패턴으로 구현하였는데 잘 지켜졌는지 궁금합니다
  * 전체적으로 봤을 때 잘 지키셨지만 아쉬운 부분이 보입니다. 예를 들면 Controller에서 해야할 메서드를 model에 하는 경우도 있는 것 같아요. 각 레이어의 역할을 알고 침범한 영역에 대해 고민하시고 수정하시면 좋을 것 같아요.
* controller 테스트 코드를 작성하는데 어려움을 느끼고 결국 완성하지 못했습니다, 테스트 코드를 잘 작성하기 위해서 어떤식으로 코드의 구성과 접근방식이 궁금합니다
  * 컨트롤러가 모델과 뷰를 중개하는 역할이라 해당 객체를 어떻게 주입할지 고민이 많으실 것 같습니다. 이런 문제를 해결하기 위해 Mock 객체를 생성하기 위한 Mockito라는 라이브러리도 있구요. 이번 과제에서는 Mockito를 쓸 수 없으니 우진님이 View와 Model을 생성해서 Controller에 주입하여 각 메서드에 대해 테스트 코드를 작성하시면 좋을 것 같습니다. 이 과정에서 왜 단위 테스트에서 Mock 객체가 중요한지 알 수 있으실 거에요.
* 또한 객체 설계에 많은 고민을 했었습니다 페어와 많은 상의를 했었을때 Car, Cars, Race, MoveDecider 이렇게 모델을 4개로 분리했었는데 많은 상의 끝에 지금 제출한 형태로 3개가 되었습니다 모델 분리에 있어서 피드백을 받고싶습니다!
  * 모델만 봤을 때 MoveDecider 가 모델의 역할을 하는지 의문이 들어요. 해당 클래스는 Controller의 역할을 하는 것같아 없애도 될 것 같습니다. 그 외 Car와 Cars로 분리한 것도 괜찮은 방향인 것 같아요 하지만 메서드를 볼 때 '모델의 메서드'라기 보다는 '컨트롤러의 메서드'의 느낌이 나는 메서드가 몇개 보이네요. 역할을 고민하시고 범위를 이동하시는 것을 추천드려요.

2024-04-11 07:53 UTC, HanHyunsoo commented on src/main/java/racingcar/exception/ErrorMessage.java
> +public enum ErrorMessage {
Enum으로 메세지들을 관리하는 것이 되게 좋네요.

하지만 Input에서 발생하는 모든 예외를 IllegalArgumentException와 EnumMessage로 처리하는 것 보다는 IllegalArgumentException를 상속한 예외클래스들을 만들어서 각 케이스에 대한 예외 클래스들을 만들면 좀 더 객체 지향적으로 변할 것 같아요. 리팩토링 해보세요!

2024-04-11 07:53 UTC, HanHyunsoo commented on src/main/java/racingcar/model/Car.java
> +    private StringBuilder moveAmount;
Car라는 모델에 집중해서 봤을때 StringBuilder가 클래스 변수로 필요한지 의문이 들어요. OutputView에 역할을 위임하는게 더 좋을 것같아요.

2024-04-11 07:53 UTC, HanHyunsoo commented on src/main/java/racingcar/model/Cars.java
> +    private void sortCarsByDistance() {
정렬 방식으로 우승자를 구하는 것도 좋지만 원본 Car 리스트가 정렬이 되어 데이터들의 일관성이 헤쳐지는 문제가 있을 것 같아요. 새로운 리스트로 반환해서 원본 리스트 순서를 유지하는 것이 더 좋을 것 같습니다.

2024-04-11 07:53 UTC, HanHyunsoo commented on src/main/java/racingcar/model/Cars.java
> +        while (i < cars.size() && maxDistance == cars.get(i).getDistance()) {
while문 대신 다른 것으로 리팩토링 하면 좋을 것 같아요. while의 단점은 조건에 따라서 무한 루프가 발생할 수 있기 때문에(해당 코드는 무한루프가 발생하는 케이스는 없지만) 다른 방향으로 리팩토링 해보세요!

2024-04-11 07:53 UTC, HanHyunsoo commented on src/test/java/racingcar/exception/ValidateInputDataTest.java
> +class ValidateInputDataTest {
각 메서드 별로 성공 케이스 뿐만아니라 실패 케이스도 만들어보세요!

2024-04-11 07:53 UTC, HanHyunsoo commented on src/main/java/racingcar/model/Car.java
> +    public void move(boolean isMove) {
이 메서드에서 boolean 매개변수가 필요할 것 같지는 않아요. controller 단에서 랜덤값을 검증하고 distance를 추가하면 model 역할로 더 맞을 것 같습니다.

2024-04-11 07:53 UTC, HanHyunsoo commented on src/main/java/racingcar/controller/RaceController.java
> +        names.forEach(cars::addCar);
리스트 메서드 중 addAll로 리팩터링 하셔도 될거같아요.

2024-04-11 07:53 UTC, HanHyunsoo commented on src/main/java/racingcar/controller/RaceController.java
> +        for (int i = 0; i < cars.getCars().size(); i++) {
for each 문으로 리팩토링 하시면 좋을 것 같습니다.

2024-04-14 09:12 UTC, woogym commented on src/main/java/racingcar/controller/RaceController.java
> +        names.forEach(cars::addCar);
각각의 리뷰해주신 댓글을 순서대로 리팩토링 해봤습니다
1. Vailidator 클래스를 각각의 입력받는 역할에 따라서 분리하고 RacingGameValidationException에서 IllegalArgumentException상속을 받아서 예외를 검증하는 방식으로 리팩토링 해봤습니다

2. outputView에서 generateDistanceString 메소드를 새롭게 만들어서 거리를 표시하는 로직의 책임을
outputView에게 가지도록 했습니다.
다만 이렇게 작성하면서 코드의 오용성에 대해서 생각하게 되었습니다
코드의 재사용성: 이부분은 outputView에서 private로 선언해서 접근 제어자를 활용해 재사용성에 대해서는 해결했습니다.
테스트 용이성: 코드의 재사용성에 대해서 해결하다보니 접근제어자로 private를 채택했기에 해당 메소드에 대한 테스트 용이성이 현저히 떨어졌습니다..
코드의 확장성: 코드의 확장성에 대해서는 문자를 매개변수로 받거나 하는 방식으로 전략을 고를 수 있을 것 같다는 생각이 들었지만 이 역시 코드로는 잘 작성이 되지 않아서 포기했습니다.

위와 같은 고민(?)을 하게되었는데 해당 부분에 대해서 피드백을 받고싶습니다!

3. sortedCarsByDistance 메소드를 새로운 리스트로 반환하는 형태로 수정했습니다
Stream을 이용했고 findWinners에서 정렬된 sortedCars를 리스트를 새로 만들어서 관리해서
원본 리스트의 순서를 유지하고 데이터의 일관성을 유지할 수 있도록 리팩토링했습니다.

4.  해당 부분도 stream의 filter를 이용해서 로직을 수정했습니다.

5. 정상적인 입력이 주어졌을때의 케이스를 말씀하신거 같은데 잘못 말씀하신거 같아서
일단은 제가 이해한바로 정상적인 입력이 이루어졌을때의 예외가 던져지지 않는지에 대한
테스트 코드를 작성해봤습니다.

6. 수정했습니다! 다시 생각해보니 Car라는 모델에서 움직임을 자체적으로 판단하기보다는
controller에서 움직임을 판별하고 지시해서 움직이거나 멈추거나로 하는게 맞는거 같습니다

7. 해당 부분은 조금은 다른 방식으로 리팩토링 해봤습니다
Cars클래스에서 addCar메소드를 활용해서 addAllCar메소드를 만들어서
Cars 클랙스에 List<String>으로 받아서 여러 자동차를 추가하는 메소드를 구현해봤습니다
addAllCars를 통해서 getCars 메소드는 자동차 이름 리스트를 한 번에 받을 수 있도록 했습니다
기존 코드보다 Cars의 인스턴스에 자동차를 추가하는 과정이 조금은 더 가독성이 있어 보이도록
수정해봤습니다.

8. 6번 내용을 수정하면서 같이 수정했습니다! 아직은 그냥 for문을 사용하는게 더 익숙해서
해당 부분의 코드를 작성할 때 저렇게 작성한 것 같습니다
어떻때 for문과 foreach문을 어떤 상황때 사용하는게 더 효과적일지 어떨때는 더 좋지 않을지에
대해서 찾아보겠습니다

9. 마지막으로 Controller에 있어서 간단한 테스트 코드를 구현해봤습니다
우승자를 찾고 출력하는것과, 이동거리를 표시하는 테스트 코드드는 CarTest와 CarsTest에서 이미 검증하고 있어서 startGame에 있어서만 테스트 코드를 작성했습니다
그래도 게임이 끝가지 잘 구동이 되는지를 검사하고 싶어서 찾아보니
controller에서 참조하고 있는 outputView는 이동거리를 표시하고 우승자를 색출하는 결과물을
System.out.print()문을 사용해서 직접적으로 콘솔창에 출력하는 메소드여서 
sysout메소드 와 같은 경우는 직접적으로 단위테스트를 할 수 없다고 찾을수 있었습니다
그래서 이동거리와 우승자 선별은 CarTest, CarsTest에서 하고 있기에 어느정도 충당이 된다고 생각하여
없앴습니다.

2024-05-10 02:10 UTC, hangillee commented
잘 리팩토링 한 것 같습니다. 미션 고생 많으셨어요!

2024-05-10 02:10 UTC, merged